apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ssh-proxy
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: ssh-proxy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ssh-proxy
subjects:
- kind: ServiceAccount
  name: default
  namespace: ssh-proxy

---
kind: Deployment
apiVersion: apps/v1
metadata:

  name: ssh-proxy
  namespace: ssh-proxy
  labels:
    app: ssh-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
     app: ssh-proxy
  template:
    metadata:
      labels:
        app: ssh-proxy
    spec:
      containers:
      - name: ssh-proxy
        image: sshserver:0.4
        ports:
        - containerPort: 22
---
kind: Service
apiVersion: v1
metadata:
  name: ssh-proxy
  namespace: ssh-proxy
  labels:
   app: ssh-proxy
spec:
  type: NodePort 
  selector:
    app: ssh-proxy
  ports:
  - port: 22
    targetPort: 22
    protocol: TCP
    nodePort: 30022
