apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.user }}
  labels:
    app: {{ .Values.user }}
spec:
  ports:
  - port: 22
    name: ssh
  clusterIP: None
  selector:
    app: {{ .Values.user }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.user }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.user }} # 必须匹配 .spec.template.metadata.labels
  serviceName: "{{ .Values.user }}"
  replicas: 1 # 默认值是 1
  template:
    metadata:
      labels:
        app: {{ .Values.user }} # 必须匹配 .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: ssh 
        image: {{ .Values.image }}
        ports:
        - containerPort: 22
          name: ssh
        command: ["/bin/sh"]
        args: ["-c", "useradd -d /home/{{ .Values.user }} -m {{ .Values.user }} ; echo \"{{ .Values.user }}:{{ .Values.pass }}\" | chpasswd ; /usr/sbin/sshd -D -e"]
